### ISSUE TITLE
throw-promise! for pipeline (for helix suspense boundary) forces component to re-render on pipeline start and stop

### ISSUE THREAD

**Issue by xlfe** [keechma/keechma-next-toolbox#5]
Thanks for all your work on keechma-*

I'm using keechma-next with helix and I have the following setup

A react suspense boundary (using helix/suspense)
A child component with a throw-promise! and a reference to a keechma-pipeline

That works - ie while the pipeline is running, the :fallback from the suspense boundary is rendered (awesome by the way!)

I'm seeing a problem though where (I think) the component is re-rendering (because the hooks are being called presumably) when the state hasn't changed. 

I can trigger a re-render just by calling dispatch to an empty pipeline. 

Adding a debug after the throw-promise such as

```clojure
(debug (use-meta-sub props cname))   
```

Shows can see the meta-state changing during the re-render
```
{:keechma.next.controllers.pipelines/state {:keechma.on/start []}}
```
to
```
{:keechma.next.controllers.pipelines/state {:keechma.on/start [], :load-page []}}
```

So, while it's not a bug that the hook generated by use-meta-sub is being called here, it does mean that throw-promise! is causing performance issues when combined with pipelines (because it's giving 2+ un-necessary re-renders).

I'm mulling over what a fix might be, but thought I'd post here too

**Comment by xlfe** [comment]
I tried adding a processor to the use-meta-sub to limit changes to the pipeline of interest : 
```clojure
(defn processor
  [state]
  (let [k :keechma.next.controllers.pipelines/state
        f (update state k select-keys [:keechma.on/start])]
    f))

(defnc render
 [props]
 (throw-promise! (use-meta-sub props tctrl/cname processor) :keechma.on/start)
```

But I'm still getting a re-render triggered when I dispatch an event to an un related emptry pipeline (on the same controller) eg (dispatch props tctrl/cname :load-page blah)

**Comment by retro** [comment]
@xlfe This is happening for a few reasons:

1. Pipelines are tracking a lot of state in their runtime
2. Keechma is using `identical?` for equality checks to determine which subscriptions to call
3. Keechma has strict evaluation, so each change will trigger re-render

All of these choices are made to make React integration easier. IIRC both Reagent and Rum had issues when they added their own async rendering pipeline on top of React.

So, even if you have an empty pipeline (or pipeline that has only synchronous forms), you will get two extra writes to the pipeline runtime state atom, once the pipeline is started, and second one when it's done. 

https://github.com/keechma/keechma-pipelines/blob/master/src/keechma/pipelines/runtime.cljs#L431
https://github.com/keechma/keechma-pipelines/blob/master/src/keechma/pipelines/runtime.cljs#L416

Keechma controller is adding a watcher to the pipeline runtime atom, which is then updating controller's meta-state*

https://github.com/keechma/keechma-next-toolbox/blob/master/src/keechma/next/controllers/pipelines.cljs#L37

I think we might fix this problem by updating the watcher to check if the previous value is `=` to the new value and then avoid the `swap!` call. Since the number of active pipelines should be pretty small at any point in time, `=` call should be cheap enough.

**Comment by retro** [comment]
@xlfe I think I've managed to fix it in user space without changing any Keechma or Keechma toolbox code. https://github.com/retro/keechma-pipelines-throw-promise/blob/master/src/app/ui/main.cljs#L11 Is this solving your problem?

**Comment by xlfe** [comment]
@retro I think that does the trick - thank you!
